/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedFeatureFlagsRouteImport } from './routes/_authenticated/feature-flags'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated/incidents'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedDeploymentsIndexRouteImport } from './routes/_authenticated/deployments.index'
import { Route as AuthenticatedFeatureFlagsIndexRouteImport } from './routes/_authenticated/feature-flags.index'
import { Route as AuthenticatedIncidentsIndexRouteImport } from './routes/_authenticated/incidents.index'
import { Route as AuthenticatedIncidentsIncidentIdRouteImport } from './routes/_authenticated/incidents.$incidentId'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs.index'
import { Route as AuthenticatedServicesIndexRouteImport } from './routes/_authenticated/services.index'
import { Route as AuthenticatedServicesServiceIdRouteImport } from './routes/_authenticated/services.$serviceId'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeatureFlagsRoute =
  AuthenticatedFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeploymentsIndexRoute =
  AuthenticatedDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDeploymentsRoute,
  } as any)
const AuthenticatedFeatureFlagsIndexRoute =
  AuthenticatedFeatureFlagsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFeatureFlagsRoute,
  } as any)
const AuthenticatedIncidentsIndexRoute =
  AuthenticatedIncidentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedIncidentsIncidentIdRoute =
  AuthenticatedIncidentsIncidentIdRouteImport.update({
    id: '/$incidentId',
    path: '/$incidentId',
    getParentRoute: () => AuthenticatedIncidentsRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLogsRoute,
} as any)
const AuthenticatedServicesIndexRoute =
  AuthenticatedServicesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedServicesServiceIdRoute =
  AuthenticatedServicesServiceIdRouteImport.update({
    id: '/$serviceId',
    path: '/$serviceId',
    getParentRoute: () => AuthenticatedServicesRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/deployments': typeof AuthenticatedDeploymentsRouteWithChildren
  '/feature-flags': typeof AuthenticatedFeatureFlagsRouteWithChildren
  '/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/logs': typeof AuthenticatedLogsRouteWithChildren
  '/services': typeof AuthenticatedServicesRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/deployments/': typeof AuthenticatedDeploymentsIndexRoute
  '/feature-flags/': typeof AuthenticatedFeatureFlagsIndexRoute
  '/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/services/': typeof AuthenticatedServicesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/': typeof AuthenticatedIndexRoute
  '/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/deployments': typeof AuthenticatedDeploymentsIndexRoute
  '/feature-flags': typeof AuthenticatedFeatureFlagsIndexRoute
  '/incidents': typeof AuthenticatedIncidentsIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRouteWithChildren
  '/_authenticated/feature-flags': typeof AuthenticatedFeatureFlagsRouteWithChildren
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRouteWithChildren
  '/_authenticated/logs': typeof AuthenticatedLogsRouteWithChildren
  '/_authenticated/services': typeof AuthenticatedServicesRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/incidents/$incidentId': typeof AuthenticatedIncidentsIncidentIdRoute
  '/_authenticated/services/$serviceId': typeof AuthenticatedServicesServiceIdRoute
  '/_authenticated/deployments/': typeof AuthenticatedDeploymentsIndexRoute
  '/_authenticated/feature-flags/': typeof AuthenticatedFeatureFlagsIndexRoute
  '/_authenticated/incidents/': typeof AuthenticatedIncidentsIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/deployments'
    | '/feature-flags'
    | '/incidents'
    | '/logs'
    | '/services'
    | '/settings'
    | '/users'
    | '/incidents/$incidentId'
    | '/services/$serviceId'
    | '/deployments/'
    | '/feature-flags/'
    | '/incidents/'
    | '/logs/'
    | '/services/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/settings'
    | '/'
    | '/incidents/$incidentId'
    | '/services/$serviceId'
    | '/deployments'
    | '/feature-flags'
    | '/incidents'
    | '/logs'
    | '/services'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/deployments'
    | '/_authenticated/feature-flags'
    | '/_authenticated/incidents'
    | '/_authenticated/logs'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/'
    | '/_authenticated/incidents/$incidentId'
    | '/_authenticated/services/$serviceId'
    | '/_authenticated/deployments/'
    | '/_authenticated/feature-flags/'
    | '/_authenticated/incidents/'
    | '/_authenticated/logs/'
    | '/_authenticated/services/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feature-flags': {
      id: '/_authenticated/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof AuthenticatedFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deployments/': {
      id: '/_authenticated/deployments/'
      path: '/'
      fullPath: '/deployments/'
      preLoaderRoute: typeof AuthenticatedDeploymentsIndexRouteImport
      parentRoute: typeof AuthenticatedDeploymentsRoute
    }
    '/_authenticated/feature-flags/': {
      id: '/_authenticated/feature-flags/'
      path: '/'
      fullPath: '/feature-flags/'
      preLoaderRoute: typeof AuthenticatedFeatureFlagsIndexRouteImport
      parentRoute: typeof AuthenticatedFeatureFlagsRoute
    }
    '/_authenticated/incidents/': {
      id: '/_authenticated/incidents/'
      path: '/'
      fullPath: '/incidents/'
      preLoaderRoute: typeof AuthenticatedIncidentsIndexRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/incidents/$incidentId': {
      id: '/_authenticated/incidents/$incidentId'
      path: '/$incidentId'
      fullPath: '/incidents/$incidentId'
      preLoaderRoute: typeof AuthenticatedIncidentsIncidentIdRouteImport
      parentRoute: typeof AuthenticatedIncidentsRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedLogsRoute
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof AuthenticatedServicesIndexRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/services/$serviceId': {
      id: '/_authenticated/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdRouteImport
      parentRoute: typeof AuthenticatedServicesRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
  }
}

interface AuthenticatedDeploymentsRouteChildren {
  AuthenticatedDeploymentsIndexRoute: typeof AuthenticatedDeploymentsIndexRoute
}

const AuthenticatedDeploymentsRouteChildren: AuthenticatedDeploymentsRouteChildren =
  {
    AuthenticatedDeploymentsIndexRoute: AuthenticatedDeploymentsIndexRoute,
  }

const AuthenticatedDeploymentsRouteWithChildren =
  AuthenticatedDeploymentsRoute._addFileChildren(
    AuthenticatedDeploymentsRouteChildren,
  )

interface AuthenticatedFeatureFlagsRouteChildren {
  AuthenticatedFeatureFlagsIndexRoute: typeof AuthenticatedFeatureFlagsIndexRoute
}

const AuthenticatedFeatureFlagsRouteChildren: AuthenticatedFeatureFlagsRouteChildren =
  {
    AuthenticatedFeatureFlagsIndexRoute: AuthenticatedFeatureFlagsIndexRoute,
  }

const AuthenticatedFeatureFlagsRouteWithChildren =
  AuthenticatedFeatureFlagsRoute._addFileChildren(
    AuthenticatedFeatureFlagsRouteChildren,
  )

interface AuthenticatedIncidentsRouteChildren {
  AuthenticatedIncidentsIncidentIdRoute: typeof AuthenticatedIncidentsIncidentIdRoute
  AuthenticatedIncidentsIndexRoute: typeof AuthenticatedIncidentsIndexRoute
}

const AuthenticatedIncidentsRouteChildren: AuthenticatedIncidentsRouteChildren =
  {
    AuthenticatedIncidentsIncidentIdRoute:
      AuthenticatedIncidentsIncidentIdRoute,
    AuthenticatedIncidentsIndexRoute: AuthenticatedIncidentsIndexRoute,
  }

const AuthenticatedIncidentsRouteWithChildren =
  AuthenticatedIncidentsRoute._addFileChildren(
    AuthenticatedIncidentsRouteChildren,
  )

interface AuthenticatedLogsRouteChildren {
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
}

const AuthenticatedLogsRouteChildren: AuthenticatedLogsRouteChildren = {
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
}

const AuthenticatedLogsRouteWithChildren =
  AuthenticatedLogsRoute._addFileChildren(AuthenticatedLogsRouteChildren)

interface AuthenticatedServicesRouteChildren {
  AuthenticatedServicesServiceIdRoute: typeof AuthenticatedServicesServiceIdRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
}

const AuthenticatedServicesRouteChildren: AuthenticatedServicesRouteChildren = {
  AuthenticatedServicesServiceIdRoute: AuthenticatedServicesServiceIdRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
}

const AuthenticatedServicesRouteWithChildren =
  AuthenticatedServicesRoute._addFileChildren(
    AuthenticatedServicesRouteChildren,
  )

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRouteWithChildren
  AuthenticatedFeatureFlagsRoute: typeof AuthenticatedFeatureFlagsRouteWithChildren
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRouteWithChildren
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRouteWithChildren
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRouteWithChildren,
  AuthenticatedFeatureFlagsRoute: AuthenticatedFeatureFlagsRouteWithChildren,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRouteWithChildren,
  AuthenticatedLogsRoute: AuthenticatedLogsRouteWithChildren,
  AuthenticatedServicesRoute: AuthenticatedServicesRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
